---
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: dist.zip
    dest: ~/backend-app

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend-app
    unzip dist.zip
    rm -rf dist.zip

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    # Use n version manager to use Node.js v13.8.0
    sudo npm install --global n
    sudo n 13.8.0

- name: "Executing node app with PM2"
  shell: |
    export
    cd ~/backend-app
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
